/* This file was generated by ../build-aux/gen_build_data.sh.  Do not edit manually.  */
package net.opentsdb.tools;

/** Build data for {@code net.opentsdb.tools} */
public final class BuildData {
  /** Version string MAJOR.MINOR.MAINT */
  public static final String version = "2.3.0";
  /** Short revision at which this package was built. */
  public static final String short_revision = "cac608a";
  /** Full revision at which this package was built. */
  public static final String full_revision = "cac608ad7bfaf6315fd2319a8af37da307abdeb9";
  /** UTC date at which this package was built. */
  public static final String date = "2016/12/29 13:57:15 +0000";
  /** UNIX timestamp of the time of the build. */
  public static final long timestamp = 1483019835;

  /** Represents the status of the repository at the time of the build. */
  public static enum RepoStatus {
    /** The status of the repository was unknown at the time of the build. */
    UNKNOWN,
    /** There was no local modification during the build. */
    MINT,
    /** There were some local modifications during the build. */
    MODIFIED;
  }
  /** Status of the repository at the time of the build. */
  public static final RepoStatus repo_status = RepoStatus.MINT;

  /** Username of the user who built this package. */
  public static final String user = "root";
  /** Host on which this package was built. */
  public static final String host = "centos.localhost";
  /** Path to the repository in which this package was built. */
  public static final String repo = "/home/hobbes/opentsdb_OFFICIAL/build";
  /** Git branch */
  public static final String branch = "master";

  /** Human readable string describing the revision of this package. */
  public static final String revisionString() {
    return "net.opentsdb.tools 2.3.0 built at revision cac608a (MINT)";
  }


  /** Human readable string describing the build information of this package. */
  public static final String buildString() {
    return "Built on 2016/12/29 13:57:15 +0000 by root@centos.localhost:/home/hobbes/opentsdb_OFFICIAL/build";
  }

  // These functions are useful to avoid cross-jar inlining.

  /** Version string MAJOR.MINOR.MAINT */
  public static String version() {
    return version;
  }
  /** Short revision at which this package was built. */
  public static String shortRevision() {
    return short_revision;
  }
  /** Full revision at which this package was built. */
  public static String fullRevision() {
    return full_revision;
  }
  /** UTC date at which this package was built. */
  public static String date() {
    return date;
  }
  /** UNIX timestamp of the time of the build. */
  public static long timestamp() {
    return timestamp;
  }
  /** Status of the repository at the time of the build. */
  public static RepoStatus repoStatus() {
    return repo_status;
  }
  /** Username of the user who built this package. */
  public static String user() {
    return user;
  }
  /** Host on which this package was built. */
  public static String host() {
    return host;
  }
  /** Path to the repository in which this package was built. */
  public static String repo() {
    return repo;
  }

  // Can't instantiate.
  private BuildData() {}

  public static void main(String[] args) {
    System.out.println(revisionString());
    System.out.println(buildString());
  }
}
